In [3]:
import numpy as np
m=np.array([2,1,3,2,4])
print(m)

[2 1 3 2 4]


In [6]:
mp=np.arange(81).reshape(9,9)
print(mp)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]]


In [8]:
print(mp[:3,:3])

[[ 0  1  2]
 [ 9 10 11]
 [18 19 20]]


In [11]:
r=3
c=3
i=0
kn=np.array()

for n in range(3):
    j=0
    for k in range(3):
        if(c<=9):
            print(mp[i:r,j:c])
            j=c
            c=c+3
        else:
            print(mp[i:r,j:])
    i=r
    r=r+3
    
        
    

TypeError: Required argument 'object' (pos 1) not found

In [14]:

def my():
       
    r=3
    c=3
    i=0
    

    for n in range(3):
        j=0
        for k in range(3):
            if(c<=9):
                print(mp[i:r,j:c])
                j=c
                c=c+3
            else:
                print(mp[i:r,j:])
        i=r
        r=r+3
my()

        
    

[[ 0  1  2]
 [ 9 10 11]
 [18 19 20]]
[[ 3  4  5]
 [12 13 14]
 [21 22 23]]
[[ 6  7  8]
 [15 16 17]
 [24 25 26]]
[[27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]]
[[27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]]
[[27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]]
[[54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]]
[[54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]]
[[54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]]


In [16]:
print(mp)
def my():
       
    r=3
    c=3
    i=0
    

    for n in range(3):
        j=0
        for k in range(3):
            if(c<=9):
                print(mp[i:r,j:c])
                j=c
                c=c+3
            else:
                print(mp[i:r,j:])
                break
        i=r
        r=r+3
my()

        
    

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]]
[[ 0  1  2]
 [ 9 10 11]
 [18 19 20]]
[[ 3  4  5]
 [12 13 14]
 [21 22 23]]
[[ 6  7  8]
 [15 16 17]
 [24 25 26]]
[[27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]]
[[54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]]


In [17]:
print(mp)
def my():
       
    r=3
    c=3
    i=0
    

    for n in range(3):
        j=0
        for k in range(3):
            if(c<=9):
                print(mp[i:r,j:c])
                j=c
                c=c+3
            else:
                print(mp[i:r,j:])
                break
        i=r
        r=r+3
my()

        
    

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]]
[[ 0  1  2]
 [ 9 10 11]
 [18 19 20]]
[[ 3  4  5]
 [12 13 14]
 [21 22 23]]
[[ 6  7  8]
 [15 16 17]
 [24 25 26]]
[[27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]]
[[54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]]


In [22]:
print(mp)
def my():
       
    r=3
    c=3
    i=0
    

    for n in range(9):
        j=0
        for k in range(3):
            if(c<=9):
                print(mp[i:r,j:c])
                j=c
                c=c+3
        if(r<=9):
            i=r
            r=r+3
my()

        
    

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]]
[[ 0  1  2]
 [ 9 10 11]
 [18 19 20]]
[[ 3  4  5]
 [12 13 14]
 [21 22 23]]
[[ 6  7  8]
 [15 16 17]
 [24 25 26]]


# print(mp)
def my():
       
    r=3
    c=3
  
    

    for i in range(len(mp)):
        j=0
        for k in range(3):
            if(c<=9):
                print(mp[i:r,j:c])
                
                j=c
                c=c+3
        
        if(r<=9):
            i=r
            r=r+3
            
my()

        
    

# fancy indexing
# arraname[[rowcoordinates],[cplumnco ordinates]]


In [28]:
arr=np.arange(10,100,10)
arr=np.reshape(arr,(3,3))
print(arr)


[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [30]:
print(arr[[0,1,2,1,1,0],[1,0,1,2,1,2]])

[20 40 80 60 50 30]


In [32]:
#boolean indexing
print(arr[arr%12==0])
#for greater than 60
print(arr[arr>60])





[60]
[70 80 90]


In [40]:
#full concept
m1=np.full((3,3),7)
print(m1)
m2=np.full((3,3),2)
print(m2)

#to concatenate
np.concatenate((m1,m2))
#to concatenate horizontally
np.concatenate((m1,m2),axis=1)

#vstack stack array vertically
np.vstack((m1,m2))
#hstack for stacking horizontally,stack array horizontall
np.hstack((m1,m2))
np.r_[m1,m2]#stack vertically
np.c_[m1,m2]#to arrange/stack horizontally/columnwise

np.row_stack((m1,m2))
'''
output

[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]
array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])
'''

[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]


'\noutput\n\n[[7 7 7]\n [7 7 7]\n [7 7 7]]\n[[2 2 2]\n [2 2 2]\n [2 2 2]]\narray([[7, 7, 7],\n       [7, 7, 7],\n       [7, 7, 7],\n       [2, 2, 2],\n       [2, 2, 2],\n       [2, 2, 2]])\n'

In [43]:
#splitting
#hsplit()
np.hsplit(arr,3)
'''

[array([[10],
        [40],
        [70]]), array([[20],
        [50],
        [80]]), array([[30],
        [60],
        [90]])]
'''
#vsplit()
np.vsplit(arr,3)
'''

[array([[10, 20, 30]]), array([[40, 50, 60]]), array([[70, 80, 90]])]
'''



'\n\n[array([[10, 20, 30]]), array([[40, 50, 60]]), array([[70, 80, 90]])]\n'

In [49]:
a=np.array([12,31,3])
a1=np.array([12,31,3])
a2=np.array([12,31,3])
a1=np.array([12,31,3])
a4=np.array([a,a2,a2,a1])

print(a4)

[[12 31  3]
 [12 31  3]
 [12 31  3]
 [12 31  3]]


In [50]:
appendarray=np.append(m1,m2,axis=0)
print("appended array is ")
print(appendarray)

appended array is 
[[7 7 7]
 [7 7 7]
 [7 7 7]
 [2 2 2]
 [2 2 2]
 [2 2 2]]


In [53]:
#insert concept
#syntax: 
#np.insert(array-name1,index,array-name2,axis)
insertedArray=np.insert(m1,1,m2,axis=0)
print(insertedArray)

[[7 7 7]
 [2 2 2]
 [2 2 2]
 [2 2 2]
 [7 7 7]
 [7 7 7]]


In [56]:
#how to delete
deletedArray=np.delete(m1,1)
print(deletedArray)
#to remove column
np.delete(m1,1,axis=1)
#broadcasting


[7 7 7 7 7 7 7 7]


array([[7, 7],
       [7, 7],
       [7, 7]])