In [1]:
#index , order 
import numpy as np
arr=np.array([10,20,40,50])
print('type of arr is', type(arr))

type of arr is <class 'numpy.ndarray'>


In [ ]:
print(arr*2)

[ 20  40  80 100]


In [ ]:
lr=[1000,2000,3700,1300]
lm=[10,56,67,23]
rarr=np.array(lr)
marr=np.array(lm)
print('---Avg number of runs---')
print(rarr/marr)

---Avg number of runs---
[100.          35.71428571  55.2238806   56.52173913]


In [ ]:
print('Dimension of array is',arr.ndim)
print('Element size in array is',arr.itemsize)
print('Element data type in array is',arr.dtype)

Dimension of array is 1
Element size in array is 8
Element data type in array is int64


In [ ]:
arr=np.array([10,20,40,50], dtype=np.float64)
print('type of arr is', arr)
print('Element size in array is',arr.itemsize)


type of arr is [10. 20. 40. 50.]
Element size in array is 8


In [ ]:
print('Shape of array ',arr.shape)

Shape of array  (4,)


In [ ]:
# asarray()
arr1=np.asarray([10,20,30,50])
print(arr1)
print(type(arr1))

[10 20 30 50]
<class 'numpy.ndarray'>


In [ ]:
i=int(input('enter index to get value'))
print('Value at given index is',arr1[i])

enter index to get value-1
Value at given index is 50


In [ ]:
i=int(input('enter index to get value'))
v=int(input('enter value for given index'))
arr1[i]=v
print('Array after update is',arr1)

enter index to get value1
enter value for given index100
Array after update is [ 10 100  30  50]


In [ ]:
print('Value in given range',arr1[1:3])
print('Value in given range',arr1[: :-1])
print('Value in given range',arr1[0: :2])

Value in given range [100  30]
Value in given range [ 50  30 100  10]
Value in given range [10 30]


In [ ]:
# arange (start, end , step) start= 0 , step = 1
# end will be excluded
arr2=np.arange(1,10)
print("Array in given range is",arr2)
print('Shape of array is',arr2.shape)
arr3=np.arange(10,100,10)
print("Array in given range is",arr3)
print('Shape of array is',arr2.shape)

Array in given range is [1 2 3 4 5 6 7 8 9]
Shape of array is (9,)
Array in given range is [10 20 30 40 50 60 70 80 90]
Shape of array is (9,)


In [ ]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("--Matrix 1---")
print(mat)

--Matrix 1---
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print('Shape of matrix',mat.shape)

Shape of matrix (3, 3)


In [ ]:
# arrayname[rowindex][columnindex]
print('Value at given column in row is',mat[2][2])

Value at given column in row is 9


In [ ]:
mat[0][2]=50
print('Updated matrix')
print(mat)

Updated matrix
[[ 1  2 50]
 [ 4  5  6]
 [ 7  8  9]]


In [ ]:
# zero matrix 
z = np.zeros((3,3))
print('--Zero Matrix is----')
print(z)

--Zero Matrix is----
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
z = np.zeros((3,3),dtype=np.int32)
print('--Zero Matrix is----')
print(z)

--Zero Matrix is----
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
# ones()
o= np.ones((3,3),dtype=np.int32)
print('--One Mmatrix ---')
print(o)

--One Mmatrix ---
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
n=int(input('enter number to fill in matrix'))
print(o*n)

enter number to fill in matrix11
[[11 11 11]
 [11 11 11]
 [11 11 11]]


In [ ]:
# full(shape ,element)
farray=np.full((2,3),7)
print('filled array ')
print(farray)

filled array 
[[7 7 7]
 [7 7 7]]


In [ ]:
#random matrix
rarray= np.random.random((3,3))
print('--Random array is ---')
print(rarray)

--Random array is ---
[[0.11768908 0.2138599  0.2269946 ]
 [0.9903687  0.79072767 0.51063998]
 [0.10069561 0.72333213 0.19785098]]


In [ ]:
# randint(start , end range , shape)
rarray1= np.random.randint(10,40,(3,3))
print('--Random array is ---')
print(rarray1)

--Random array is ---
[[30 39 17]
 [32 11 21]
 [23 38 16]]


In [ ]:
# identity 
iarray = np.eye(3)
print('--Identity matrix is ----')
print(iarray)

--Identity matrix is ----
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
mat2=np.array([[10,20,30],[40,50,60]])
print('--original matrix---')
print(mat2)
print('Shape of matrix ',mat2.shape)
print('---Transpose matrix is---')
print(np.transpose(mat2))

--original matrix---
[[10 20 30]
 [40 50 60]]
Shape of matrix  (2, 3)
---Transpose matrix is---
[[10 40]
 [20 50]
 [30 60]]


In [ ]:
print('---Transpose matrix is---')
print(mat2.T)

---Transpose matrix is---
[[10 40]
 [20 50]
 [30 60]]


In [ ]:
m = np.array([[10,20,30,50],[1,2,3,4]])
print('-original matrix is--')
print(m)
print('Shape of m is',m.shape)

-original matrix is--
[[10 20 30 50]
 [ 1  2  3  4]]
Shape of m is (2, 4)


In [ ]:
#reshape(object ,(shape)) - it create new array with given shape 
# while reshape number of elements of array should remain same 
rarray=np.reshape(m ,(4,2))  # (4,2) ,(8,1),(1,8),(2,4)
print('--Reshape array is ---')
print(rarray)

--Reshape array is ---
[[10 20]
 [30 50]
 [ 1  2]
 [ 3  4]]


In [ ]:
rarray1=np.reshape(m ,(1,-1))  
print('--Reshape array is ---')
print(rarray1)
print('Shape of reshape array',rarray1.shape)
print('Dimension reshaped array',rarray1.ndim)

--Reshape array is ---
[[10 20 30 50  1  2  3  4]]
Shape of reshape array (1, 8)
Dimension reshaped array 2


In [ ]:
rarray2=np.reshape(m ,(-1,1))  
print('--Reshape array is ---')
print(rarray2)
print('Shape of reshape array',rarray2.shape)

--Reshape array is ---
[[10]
 [20]
 [30]
 [50]
 [ 1]
 [ 2]
 [ 3]
 [ 4]]
Shape of reshape array (8, 1)


In [ ]:
print(m)

[[10 20 30 50]
 [ 1  2  3  4]]


In [ ]:
m.shape=(4,2)  # reshape using shape property modifies original array
print(m)

[[10 20]
 [30 50]
 [ 1  2]
 [ 3  4]]


In [ ]:
# resize(object , new shape ) 
arr=np.arange(1,10)
arr=arr.reshape(3,3)
print('original array')
print(arr)

original array
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
resizearray=np.resize(arr,(6,6))
print('--Resized array---')
print(resizearray)

--Resized array---
[[1 2 3 4 5 6]
 [7 8 9 1 2 3]
 [4 5 6 7 8 9]
 [1 2 3 4 5 6]
 [7 8 9 1 2 3]
 [4 5 6 7 8 9]]


In [ ]:
resizearray1=np.resize(arr,(2,3))
print('--Resized array---')
print(resizearray1)

--Resized array---
[[1 2 3]
 [4 5 6]]


In [ ]:
# ravel()
print('Original array')
print(m)

Original array
[[10 20]
 [30 50]
 [ 1  2]
 [ 3  4]]


In [ ]:
r=m.ravel()  
print(r)
print('Shape of array after ravel',r.shape)
print('Dimension of r',r.ndim)


[10 20 30 50  1  2  3  4]
Shape of array after ravel (8,)
Dimension of r 1


In [ ]:
m1=np.arange(11,20)
m2=np.arange(1,10)
m1=m1.reshape(3,3)
m2=m2.reshape(3,3)
add=m1+m2 
add1=np.add(m1,m2)
mul=np.multiply(m1,m2)
sub=np.subtract(m1,m2)
div=np.divide(m1,m2)
print('Sum of two matrix',add1)
print('Sub of two matrix',sub)
print('Mul of two matrix',mul)
print('Div of two matrix',div)


Sum of two matrix [[12 14 16]
 [18 20 22]
 [24 26 28]]
Sub of two matrix [[10 10 10]
 [10 10 10]
 [10 10 10]]
Mul of two matrix [[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]
Div of two matrix [[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]
 [ 2.42857143  2.25        2.11111111]]


In [ ]:
ar=np.arange(0,1.0,0.05)
print(ar)

[0.   0.05 0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5  0.55 0.6  0.65
 0.7  0.75 0.8  0.85 0.9  0.95]


In [ ]:
sarray=np.sin(ar)
carray=np.cos(ar)
print('Sin array is',sarray)

Sin array is [0.         0.04997917 0.09983342 0.14943813 0.19866933 0.24740396
 0.29552021 0.34289781 0.38941834 0.43496553 0.47942554 0.52268723
 0.56464247 0.60518641 0.64421769 0.68163876 0.71735609 0.75128041
 0.78332691 0.8134155 ]


In [ ]:
print('Cos value ',carray)

Cos value  [1.         0.99875026 0.99500417 0.98877108 0.98006658 0.96891242
 0.95533649 0.93937271 0.92106099 0.9004471  0.87758256 0.85252452
 0.82533561 0.7960838  0.76484219 0.73168887 0.69670671 0.65998315
 0.62160997 0.58168309]


In [ ]:
print(m1)
print(m2)

[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
np.dot(m1,m2)

array([[150, 186, 222],
       [186, 231, 276],
       [222, 276, 330]])

In [ ]:
m1.dot(m2)

array([[150, 186, 222],
       [186, 231, 276],
       [222, 276, 330]])

In [ ]:
import numpy as np
m=np.array([[10,20,30],[1,70,3],[40,50,60]])
print('Array is')
print(m)


Array is
[[10 20 30]
 [ 1 70  3]
 [40 50 60]]


In [ ]:
print("Maximum value in array is", np.max(m))
print("Min value in array is", np.min(m))
print("Sum value in array is", np.sum(m))
print("Mean value in array is", np.mean(m))
print("Cumsum value in array is", np.cumsum(m))

Maximum value in array is 70
Min value in array is 1
Sum value in array is 284
Mean value in array is 31.555555555555557
Cumsum value in array is [ 10  30  60  61 131 134 174 224 284]


In [ ]:
# axis = 1  it means 
print("Maximum value in array  rowwise is", np.max(m, axis=1))
print("Min value in array  row wise is", np.min(m,axis=1))
print('Sum of elemnt in array row wise is',np.sum(m,axis=1))

Maximum value in array  rowwise is [30 70 60]
Min value in array  row wise is [10  1 40]
Sum of elemnt in array row wise is [ 60  74 150]


In [ ]:
print("Maximum value in array  columnwise is", np.max(m, axis=0))
print("Min value in array  columnwise wise is", np.min(m,axis=0))
print('Sum of elemnt in array column wise is',np.sum(m,axis=0))

Maximum value in array  columnwise is [40 70 60]
Min value in array  columnwise wise is [ 1 20  3]
Sum of elemnt in array column wise is [ 51 140  93]


In [ ]:
print("Std is ",np.std(m,axis=1))

Std is  [ 8.16496581 32.06590436  8.16496581]


In [ ]:
print("Correlation coffiecient",np.corrcoef(m))

Correlation coffiecient [[1.         0.02546308 1.        ]
 [0.02546308 1.         0.02546308]
 [1.         0.02546308 1.        ]]


In [ ]:
print(m)

[[10 20 30]
 [ 1 70  3]
 [40 50 60]]


In [ ]:
np.savetxt("myarray.np",m,fmt='%.0f', delimiter=',')

In [ ]:
array =np.loadtxt("myarray.np",dtype=np.int32,skiprows=0)
print(array)

[[10 20 30]
 [ 1 70  3]
 [40 50 60]]


In [ ]:
array =np.loadtxt("myarray.txt",dtype=np.int32,skiprows=1)
print(array)

[[10 20 30]
 [ 1 70  3]
 [40 50 60]]


In [ ]:
x,y,z =np.loadtxt("myarray.txt",dtype=np.int32,skiprows=1,unpack=True)
print(x)
print(y)

[10  1 40]
[20 70 50]


In [ ]:
m.sort(axis=0)
print("sorted array")
print(m)

sorted array
[[ 1  3 30]
 [10 20 60]
 [40 50 70]]


In [ ]:
print(m)

[[ 1  3 30]
 [10 20 60]
 [40 50 70]]


In [ ]:
print("Slicing 1",m[: , 1:2])

Slicing 1 [[ 3]
 [20]
 [50]]


In [ ]:
print("Slicing 2",m[1:2 ,:])

Slicing 2 [[10 20 60]]


In [ ]:
print("Slicing 3",m[1: , 1:])

Slicing 3 [[20 60]
 [50 70]]


In [ ]:
print("Slicing 3",m[::2 , ::2])

Slicing 3 [[ 1 30]
 [40 70]]


In [ ]:
print("Slicing 4",m[2::-2 , 2::-2])

Slicing 4 [[70 40]
 [30  1]]


In [4]:
#fancy indexing 
# arraname[[row coordinates],[columnco ordinates]]
arr=np.arange(10,100,10)
arr=np.reshape(arr,(3,3))
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [5]:
print(arr[[0,1,2,1,1,0],[1,0,1,2,1,2]])

[20 40 80 60 50 30]


In [9]:
#boolean indexing
print(arr[arr%12==0 ])
print(arr[arr>60])

[60]
[70 80 90]


In [11]:
m1=np.full((3,3),7)
print(m1)
m2=np.full((3,3),2)
print(m2)

[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [14]:
np.concatenate((m1,m2))

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [15]:
np.concatenate((m1,m2),axis=1)

array([[7, 7, 7, 2, 2, 2],
       [7, 7, 7, 2, 2, 2],
       [7, 7, 7, 2, 2, 2]])

In [17]:
# vstack stack array vertically 
np.vstack((m2,m1))

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [18]:
#hstack stack array horizontally
np.hstack((m1,m2))

array([[7, 7, 7, 2, 2, 2],
       [7, 7, 7, 2, 2, 2],
       [7, 7, 7, 2, 2, 2]])

In [19]:
np.r_[m1,m2] # stack vertically

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [20]:
np.c_[m1,m2] # stack columnwise 

array([[7, 7, 7, 2, 2, 2],
       [7, 7, 7, 2, 2, 2],
       [7, 7, 7, 2, 2, 2]])

In [24]:
print(np.column_stack((m1,m2)))
print(np.row_stack((m1,m2)))

[[7 7 7 2 2 2]
 [7 7 7 2 2 2]
 [7 7 7 2 2 2]]
[[7 7 7]
 [7 7 7]
 [7 7 7]
 [2 2 2]
 [2 2 2]
 [2 2 2]]


In [25]:
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [29]:
np.hsplit(arr,3)

[array([[10],
        [40],
        [70]]), array([[20],
        [50],
        [80]]), array([[30],
        [60],
        [90]])]

In [41]:
np.vsplit(arr,3)


[array([[10, 20, 30]]), array([[40, 50, 60]]), array([[70, 80, 90]])]

In [55]:
m1=np.full((3,3),5)
m2=np.full((3,3),7)

In [56]:
appendarray=np.append(m1,m2)
print("appended array is")
print(appendarray)

appended array is
[5 5 5 5 5 5 5 5 5 7 7 7 7 7 7 7 7 7]


In [57]:
appendarray=np.append(m1,m2, axis=0)
print("appended array is")
print(appendarray)

appended array is
[[5 5 5]
 [5 5 5]
 [5 5 5]
 [7 7 7]
 [7 7 7]
 [7 7 7]]


In [58]:
appendarray=np.append(m1,m2,axis=1)
print("appended array is")
print(appendarray)

appended array is
[[5 5 5 7 7 7]
 [5 5 5 7 7 7]
 [5 5 5 7 7 7]]


In [59]:
print(m1)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [60]:
print(m2)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [72]:
insertedarray1=np.insert(m1,1,m2,axis=0)
print(insertedarray1)

[[5 5 5]
 [7 7 7]
 [7 7 7]
 [7 7 7]
 [5 5 5]
 [5 5 5]]


In [66]:
insertedarray=np.insert(m1,1,m2,axis=1)
print(insertedarray)

[[5 7 7 7 5 5]
 [5 7 7 7 5 5]
 [5 7 7 7 5 5]]


In [69]:
m3=[100,200,300]
insertedarray=np.insert(m1,1,m3)
print(insertedarray)

[  5 100 200 300   5   5   5   5   5   5   5   5]


In [75]:

deletedarray=np.delete(m1,1)
print(deletedarray)
print(insertedarray1)

[5 5 5 5 5 5 5 5]
[[5 5 5]
 [7 7 7]
 [7 7 7]
 [7 7 7]
 [5 5 5]
 [5 5 5]]


In [74]:
np.delete(insertedarray1,1 ,axis=0)

array([[5, 5, 5],
       [7, 7, 7],
       [7, 7, 7],
       [5, 5, 5],
       [5, 5, 5]])

In [76]:
np.delete(insertedarray1,1 ,axis=1)

array([[5, 5],
       [7, 7],
       [7, 7],
       [7, 7],
       [5, 5],
       [5, 5]])

In [77]:
m1

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [82]:
m3=[10,20,30]

In [83]:
m1+m3

array([[15, 25, 35],
       [15, 25, 35],
       [15, 25, 35]])

In [84]:
m1-m2

array([[-2, -2, -2],
       [-2, -2, -2],
       [-2, -2, -2]])